"""Fix conversation foreign key constraint

Revision ID: 71fae022759e
Revises: c10495cfc328
Create Date: 2025-09-11 19:16:52.912982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '71fae022759e'
down_revision: Union[str, Sequence[str], None] = 'c10495cfc328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_ibfk_1'), 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'interaction', ['interaction_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_ibfk_1'), 'conversation', 'user', ['interaction_id'], ['id'])
    # ### end Alembic commands ###
