"""Add like/dislike columns to conversation

Revision ID: 8e26c845b53c
Revises: 4474dedb0209
Create Date: 2025-10-21 14:50:08.466264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e26c845b53c'
down_revision: Union[str, Sequence[str], None] = '4474dedb0209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('is_liked', sa.Boolean(), nullable=True))
    op.add_column('conversation', sa.Column('liked_at', sa.DateTime(), nullable=True))
    op.create_index('idx_document_type', 'document_context', ['document_type'], unique=False)
    op.create_index('idx_document_user', 'document_context', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_user', table_name='document_context')
    op.drop_index('idx_document_type', table_name='document_context')
    op.drop_column('conversation', 'liked_at')
    op.drop_column('conversation', 'is_liked')
    # ### end Alembic commands ###
