"""init

Revision ID: adac31edf2bb
Revises: 
Create Date: 2025-12-05 11:52:03.688154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'adac31edf2bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('country_code', sa.String(length=6), nullable=False),
    sa.Column('currency_code', sa.Text(), nullable=False),
    sa.Column('calling_code', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('meme_type', sa.String(length=191), nullable=True),
    sa.Column('original_size', sa.Float(), nullable=False),
    sa.Column('compressed_size', sa.Float(), nullable=True),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('display_name', sa.String(length=191), nullable=False),
    sa.Column('use_case', sa.Enum('VISUALIZE', 'CHAT', name='usecase'), nullable=False),
    sa.Column('llm_model_name', sa.String(length=191), nullable=False),
    sa.Column('group_category', sa.Enum('GEMINI', 'GPT', 'KIMI', name='modelgroup'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('daily_calling_limit', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_module_active', 'module', ['is_active'], unique=False)
    op.create_index('idx_module_slug', 'module', ['slug'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('subscription_name', sa.String(length=191), nullable=False),
    sa.Column('usd_amount', sa.Float(), nullable=False),
    sa.Column('bdt_amount', sa.Float(), nullable=False),
    sa.Column('subscription_plan', sa.Enum('ESSENTIAL', 'PLUS', 'ELITE', name='subscriptionplan'), nullable=False),
    sa.Column('points_per_month', sa.Integer(), nullable=False),
    sa.Column('points_per_day', sa.Integer(), nullable=True),
    sa.Column('is_addon', sa.Boolean(), nullable=False),
    sa.Column('is_daily_refill', sa.Boolean(), nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchased_subscription',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('subscription_id', sa.String(length=191), nullable=False),
    sa.Column('paddle_subscription_id', sa.String(length=191), nullable=True),
    sa.Column('subscription_status', sa.String(length=191), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_limit',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('subscription_id', sa.String(length=191), nullable=False),
    sa.Column('daily_token_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=False),
    sa.Column('daily_ads_limit', sa.Integer(), nullable=False),
    sa.Column('ad_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('mini_model_daily_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('first_name', sa.String(length=191), nullable=False),
    sa.Column('last_name', sa.String(length=191), nullable=False),
    sa.Column('password', sa.String(length=191), nullable=True),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('account_provider', sa.Enum('EMAIL', 'GOOGLE', name='accountprovider'), nullable=True),
    sa.Column('account_type', sa.Enum('EXICUTIVE', 'SUPER_ADMIN', 'ADMIN', 'USER', 'SELLER', 'GUEST', name='useraccounttype'), nullable=False),
    sa.Column('photo_url', sa.String(length=191), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('profession_title', sa.Text(), nullable=True),
    sa.Column('education_level', sa.Text(), nullable=True),
    sa.Column('primary_city', sa.Text(), nullable=True),
    sa.Column('primary_state', sa.Text(), nullable=True),
    sa.Column('primary_address', sa.Text(), nullable=True),
    sa.Column('about_description', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('zip_code', sa.Text(), nullable=True),
    sa.Column('reset_password_pin', sa.Integer(), nullable=True),
    sa.Column('reset_password_expire_date', sa.DateTime(), nullable=True),
    sa.Column('verify_pin', sa.Integer(), nullable=True),
    sa.Column('verify_pin_expire_date', sa.DateTime(), nullable=True),
    sa.Column('verify_status', sa.Boolean(), nullable=False),
    sa.Column('current_points', sa.Integer(), nullable=False),
    sa.Column('total_points_earned', sa.Integer(), nullable=False),
    sa.Column('total_points_used', sa.Integer(), nullable=False),
    sa.Column('purchased_subscription_id', sa.String(length=191), nullable=True),
    sa.Column('country_id', sa.String(length=191), nullable=True),
    sa.Column('super_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['purchased_subscription_id'], ['purchased_subscription.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('billing_log',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('subscription_id', sa.String(length=191), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('paddle_transaction_id', sa.String(length=191), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('points_added', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('icon', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('TARGET', 'BUILD', 'QUIT', name='goaltype'), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', name='goalperiod'), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('task_days', sa.JSON(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.String(length=10), nullable=True),
    sa.Column('reminder_message', sa.Text(), nullable=True),
    sa.Column('show_memo', sa.Boolean(), nullable=False),
    sa.Column('chart_type', sa.Enum('LINE', 'BAR', 'PIE', name='charttype'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary_title', sa.String(length=500), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('text_color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_learning_profile',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('preferred_topics', sa.JSON(), nullable=True),
    sa.Column('learning_style', sa.String(length=50), nullable=True),
    sa.Column('difficulty_preference', sa.String(length=20), nullable=True),
    sa.Column('mastered_concepts', sa.JSON(), nullable=True),
    sa.Column('struggling_areas', sa.JSON(), nullable=True),
    sa.Column('learning_gaps', sa.JSON(), nullable=True),
    sa.Column('average_session_length', sa.Float(), nullable=True),
    sa.Column('preferred_question_types', sa.JSON(), nullable=True),
    sa.Column('most_productive_times', sa.JSON(), nullable=True),
    sa.Column('topic_clusters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_learning_profile_activity', 'user_learning_profile', ['last_activity'], unique=False)
    op.create_index('idx_learning_profile_user', 'user_learning_profile', ['user_id'], unique=False)
    op.create_table('user_module_permission',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('module_id', sa.String(length=191), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_insert', sa.Boolean(), nullable=False),
    sa.Column('can_update', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module')
    )
    op.create_index('idx_user_module_module', 'user_module_permission', ['module_id'], unique=False)
    op.create_index('idx_user_module_user', 'user_module_permission', ['user_id'], unique=False)
    op.create_table('user_usage',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('daily_tokens_used', sa.Integer(), nullable=False),
    sa.Column('monthly_tokens_used', sa.Integer(), nullable=False),
    sa.Column('daily_ads_shown', sa.Integer(), nullable=False),
    sa.Column('mini_model_tokens_used', sa.Integer(), nullable=False),
    sa.Column('last_token_refill', sa.DateTime(), nullable=True),
    sa.Column('last_ad_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('interaction_id', sa.String(length=191), nullable=False),
    sa.Column('role', sa.Enum('USER', 'AI', name='conversationrole'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('detected_language', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_liked', sa.Boolean(), nullable=True),
    sa.Column('liked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_context',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('media_id', sa.String(length=191), nullable=False),
    sa.Column('interaction_id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('question_structure', sa.JSON(), nullable=True),
    sa.Column('main_topics', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('subject_area', sa.String(length=100), nullable=True),
    sa.Column('question_mapping', sa.JSON(), nullable=True),
    sa.Column('answer_key', sa.JSON(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('key_concepts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_interaction', 'document_context', ['interaction_id'], unique=False)
    op.create_index('idx_document_media', 'document_context', ['media_id'], unique=False)
    op.create_index('idx_document_type', 'document_context', ['document_type'], unique=False)
    op.create_index('idx_document_user', 'document_context', ['user_id'], unique=False)
    op.create_table('goal_progress',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('goal_id', sa.String(length=191), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('interaction_share',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('original_interaction_id', sa.String(length=191), nullable=False),
    sa.Column('share_id', sa.String(length=191), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('last_visited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_interaction_id'], ['interaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_id')
    )
    op.create_table('context_usage_log',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('interaction_id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('conversation_id', sa.String(length=191), nullable=True),
    sa.Column('context_sources_used', sa.JSON(), nullable=False),
    sa.Column('context_sources_ignored', sa.JSON(), nullable=True),
    sa.Column('context_retrieval_time', sa.Float(), nullable=True),
    sa.Column('context_processing_time', sa.Float(), nullable=True),
    sa.Column('context_relevance_score', sa.Float(), nullable=True),
    sa.Column('user_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('context_utilization_rate', sa.Float(), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('response_quality', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_log_created', 'context_usage_log', ['created_at'], unique=False)
    op.create_index('idx_usage_log_interaction', 'context_usage_log', ['interaction_id'], unique=False)
    op.create_index('idx_usage_log_quality', 'context_usage_log', ['response_quality'], unique=False)
    op.create_index('idx_usage_log_user', 'context_usage_log', ['user_id'], unique=False)
    op.create_table('conversation_files',
    sa.Column('conversation_id', sa.String(length=191), nullable=False),
    sa.Column('media_id', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'media_id')
    )
    op.create_table('interaction_share_visitor',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('interaction_share_id', sa.String(length=191), nullable=False),
    sa.Column('visitor_user_id', sa.String(length=191), nullable=True),
    sa.Column('visitor_ip', sa.String(length=45), nullable=True),
    sa.Column('visitor_fingerprint', sa.String(length=191), nullable=True),
    sa.Column('reward_given', sa.Boolean(), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_share_id'], ['interaction_share.id'], ),
    sa.ForeignKeyConstraint(['visitor_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interaction_share_id', 'visitor_fingerprint', name='unique_fingerprint_visit'),
    sa.UniqueConstraint('interaction_share_id', 'visitor_ip', name='unique_ip_visit'),
    sa.UniqueConstraint('interaction_share_id', 'visitor_user_id', name='unique_user_visit')
    )
    op.create_table('point_transaction',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point_transaction')
    op.drop_table('interaction_share_visitor')
    op.drop_table('conversation_files')
    op.drop_index('idx_usage_log_user', table_name='context_usage_log')
    op.drop_index('idx_usage_log_quality', table_name='context_usage_log')
    op.drop_index('idx_usage_log_interaction', table_name='context_usage_log')
    op.drop_index('idx_usage_log_created', table_name='context_usage_log')
    op.drop_table('context_usage_log')
    op.drop_table('interaction_share')
    op.drop_table('goal_progress')
    op.drop_index('idx_document_user', table_name='document_context')
    op.drop_index('idx_document_type', table_name='document_context')
    op.drop_index('idx_document_media', table_name='document_context')
    op.drop_index('idx_document_interaction', table_name='document_context')
    op.drop_table('document_context')
    op.drop_table('conversation')
    op.drop_table('user_usage')
    op.drop_index('idx_user_module_user', table_name='user_module_permission')
    op.drop_index('idx_user_module_module', table_name='user_module_permission')
    op.drop_table('user_module_permission')
    op.drop_index('idx_learning_profile_user', table_name='user_learning_profile')
    op.drop_index('idx_learning_profile_activity', table_name='user_learning_profile')
    op.drop_table('user_learning_profile')
    op.drop_table('note')
    op.drop_table('interaction')
    op.drop_table('goal')
    op.drop_table('billing_log')
    op.drop_table('user')
    op.drop_table('usage_limit')
    op.drop_table('purchased_subscription')
    op.drop_table('subscriptions')
    op.drop_index('idx_module_slug', table_name='module')
    op.drop_index('idx_module_active', table_name='module')
    op.drop_table('module')
    op.drop_table('model')
    op.drop_table('media')
    op.drop_table('country')
    # ### end Alembic commands ###
